name: HypixelSkyblock

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
  redis:
    image: redis
  proxy:
    build: servers/proxy
    volumes:
      - ./servers/proxy/configuration:/proxy/configuration
    ports:
      - 25565:25565
  limbo:
    build:
      context: servers/game
      dockerfile: LimboDockerfile
    volumes:
      - ./servers/game/configuration:/game/configuration
    ports:
      - 65535:65535
  island:
    build:
      context: servers/game
      args:
        SERVER_TYPE: ISLAND
    volumes:
      - ./servers/game/configuration:/game/configuration
    ports:
      - 20000:20000
