name: HypixelSkyblock

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
  redis:
    image: redis
  proxy:
    build: servers/proxy
    ports:
      - 25565:25565
